version: "3.0"
services:
  consumer_container:
    build: ./consumer
    ports:
      - "3000:3000"
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: on-failure

volumes:
  mongodb_data_container: