version: "3.0"
services:

  mongo_db:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    networks: 
      - mongo-compose-network
    restart: always
  
  consumer:
    build: ./consumer
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=$DATABASE_URI
  
   # mongo_seed:
  #   env_file:
  #     - .env
  #   build:
  #     context: ./mongo-seed
  #     dockerfile: Dockerfile
  #     args:
  #       - DATABASE_URI=$DATABASE_URI
  #   depends_on:
  #       - mongo_db
  #   networks:
  #     - mongo-compose-network

volumes:
  mongo_db:

networks:
  mongo-compose-network:


